dependencies:
  - name: cassandra
    version: ^0.9.4
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    condition: provisionDataStore.cassandra
  - name: elasticsearch
    version: ^0.4.1
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    condition: provisionDataStore.elasticsearch
